name: app_my_money
description: "Projeto do semestre 2024/1 para a disciplina Desenvolvimento de Sistemas para Dispositivos Móveis."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+1
  modal_bottom_sheet: ^3.0.0
  dio: ^5.4.2+1
  http: ^1.2.1
  flutter_secure_storage: ^8.0.0
  gauge_indicator: ^0.4.3
  fl_chart: ^0.36.0

dev_dependencies:
  flutter_test:
    sdk: flutter
     flutter_lints: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  dio_http2_adapter: ^2.0.0

  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
